name: Deploy Production Build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - run: npm ci
    - run: npm run build
      env:
        CI: true

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # Deploy to the gh-pages branch
        FOLDER: build   # The folder the action should push.